function init(self)
	msg.post(".", "acquire_input_focus")
	msg.post("@render:", "use_fixed_fit_projection", { near = -1, far = 1 })

	-- load the game collection for now
	msg.post("#game_proxy", "load")
	msg.post("#game_proxy", "enable")
	print("loading game collection")
end

function on_input(self, action_id, action)
	if action_id == hash("touch") and action.pressed then
		print("Touch!")
	end
end
